# Generated by Django 5.2.5 on 2025-09-02 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('PAGA', 'Paga')], default='ABERTA', max_length=10)),
                ('origem', models.CharField(choices=[('MESA', 'Mesa'), ('BALCAO', 'Balcao'), ('VIAGEM', 'Viagem')], default='MESA', max_length=10)),
                ('observacao', models.TextField(blank=True)),
                ('desconto_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('taxa_percentual', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mesa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observacao', models.TextField(blank=True)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comanda')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
            options={
                'verbose_name': 'Item da Comanda',
                'verbose_name_plural': 'Itens da Comanda',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metodo', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CARTAO', 'Cartao'), ('PIX', 'Pix')], default='DINHEIRO', max_length=10)),
                ('troco', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comanda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
