# Generated by Django 5.2.5 on 2025-09-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comanda_itemcomanda_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcomanda',
            name='preco_unitario',
        ),
    ]
