# Generated by Django 5.2.5 on 2025-09-03 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_itemcomanda_preco_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='pagamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comanda_pagamento', to='core.pagamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='comanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.comanda'),
        ),
    ]
